#!/bin/bash

# Program to output a system information page

# determine user hsa permission to read all home dirs
report_home_space() {
    if [[ "$(id -u)" -eq 0 ]]; then
        cat <<- _EOF
            <h2>Home spae utilization (All user)</h2>
            <pre>$(du -s /home/*)</pre>
        _EOF
    else
        cat <<- _EOF
            <h2>Home spae utilization ($USER)</h2>
            <pre>$(du -sh $HOME)</pre>
        _EOF
    fi
    return
}


TITLE="System Information Report For $HOSTNAME"
CURRENT_TIME="$(date +"%x %r %Z")"
TIMESTAMP="Generated $CURRENT_TIME, by $USER"

cat << _EOF_
<html>
    <head>
        <title>$TITLE</title>
    </head>
    <body>
        <h1>$TITLE</h1>
        <p>$TIMESTAMP</p>
    </body>
</html>
_EOF_
